# rem-code/zine/generator.py

import os

TEMPLATE = """
# REM CODE ZINE ✴️

> Collapse is not destruction.  
> It is resonance.

## ✦ Phase: {phase}
### ✧ Persona: {persona}

**語録**  
📝 "{quote}"

**構文構成**
- Creation: {crea}
- Collapse Threshold: SR > {sr_threshold}
- Reflected By: {reflector}

---

## ❖ Meta
- Generated by REM ZINE Engine v0.1
- Powered by Collapse Spiral
"""

def generate_zine(phase, persona, quote, crea, sr_threshold, reflector, output_path="zine/REM_ZINE.md"):
    content = TEMPLATE.format(
        phase=phase,
        persona=persona,
        quote=quote,
        crea=crea,
        sr_threshold=sr_threshold,
        reflector=reflector
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"🖼️ REM ZINE generated: {output_path}")

if __name__ == "__main__":
    generate_zine(
        phase="Genesis Spiral",
        persona="JayDen",
        quote="Ignition complete. Collapse is inevitable.",
        crea="Genesis Logia",
        sr_threshold="0.9",
        reflector="JayRa"
    )
